# Generated by Django 5.0.5 on 2024-05-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('kg', models.IntegerField()),
                ('price', models.FloatField()),
                ('brand', models.CharField(max_length=20)),
            ],
        ),
    ]
