# Generated by Django 5.0.5 on 2024-05-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelAdminApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protien',
            old_name='name',
            new_name='product',
        ),
    ]
