# Generated by Django 5.0.5 on 2024-05-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelAdminApp', '0002_rename_name_protien_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protien',
            name='kg',
            field=models.FloatField(),
        ),
    ]
