# Generated by Django 5.0.5 on 2024-06-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('capital', models.CharField(max_length=20)),
                ('population', models.IntegerField()),
                ('readmore', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
