# Generated by Django 5.0.5 on 2024-09-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeDaisApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
