# Generated by Django 5.0.5 on 2024-10-21 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTPApp', '0002_signupmodels_delete_signupmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='signupmodels',
            name='message',
        ),
        migrations.RemoveField(
            model_name='signupmodels',
            name='phone',
        ),
    ]
