# Generated by Django 5.0.5 on 2024-10-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RTPApp', '0003_contactmodels_remove_signupmodels_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodels',
            old_name='your_name',
            new_name='name',
        ),
    ]
