# Generated by Django 5.0.5 on 2024-10-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTPApp', '0005_signupmodel_delete_signupmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodels',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
