# Generated by Django 5.0.5 on 2024-07-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ORBModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('linkedin', models.TextField()),
                ('github', models.TextField()),
                ('designation', models.TextField()),
                ('summary', models.TextField()),
                ('Experince_Company_Details', models.TextField()),
                ('experience', models.TextField()),
            ],
        ),
    ]
